[project]
name = "kesher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.1",
    "faker>=40.1.2",
    "psutil>=7.2.2",
    "requests>=2.32.5",
    "textual>=7.5.0",
]
